### ISSUE TITLE
submdspan description

### ISSUE THREAD

**Issue by seanbaxter** [kokkos/mdspan#116]
Is there an explanation for `submdspan` in English? I have no idea what to do with it. I wrote a new mdspan implementation. All the tests pass, except `test_submdspan.cpp`. 

I've implemented the `map_rank`, `first` and `last` arrays here:
https://github.com/seanbaxter/mdspan/blob/circle/circle/experimental/mdspan#L705

I get confused at this part:
> Let the pack i... denote a multidimensional index in the domain of src with ik denoting the k-th element of i..., such that ik is greater than or equal to first[k] and ik is less than last[k] for all k in the range [0,src.rank()). Let the pack j... denote a multidimensional index in the domain of sub with js denoting the s-th element of j..., such that js is equal to ik minus first[k] where map_rank[k] equals s for all s in the range [0,sub.rank()). Then sub(j...) and src(i...) refer to the same element in the codomain of src.

Why is `i...` not just the contents of `first`? Why is it "greater than or equal to `first[k]`?

Can you provide some clarification to get me over the goal line?

Edit: the `offset_size` computation is scary. Someone will have to walk me through that.

**Comment by mhoemmen** [comment]
Hi Sean!  The definition is hairy because it's declarative.  It has to say, for _any_ valid source multidimensional index `i...`, what target multidimensional index `j...` would result in `sub(j...)` and `src(i...)` referring to the same element.  We're describing the function from a valid target multiindex `j...` to a valid source multiindex `i...`.  We describe it declaratively because the description must hold for any layout.

I find it easier to start with the special case where all the arguments of `submdspan` (after the input `mdspan`) are index pairs.  In that case, `first[k]` is just the first element of the k-th pair, and `last[k]` is the second element of the k-th pair.  For example, if `src` is a rank-3 `mdspan` with extents 5, 7, and 11, then `submdspan(src, {2, 4}, {3, 6}, {4, 8})` would have `first = [2, 3, 4]` and `last = [4, 6, 8]`.

I'll break down the wording a bit.

> such that `ik` is greater than or equal to `first[k]` and `ik` is less than `last[k]` for all `k` in the range [0, `src.rank()`). 

This means that `i...` is in the subset of multidimensional indices to which the result of `submdspan` refers.  In the above example, this would make all valid `i_0` values [2, 3], all valid `i_1` values [3, 4, 5], and all valid `i_2` values [4, 5, 6, 7].

> Let the pack `j...` denote a multidimensional index in the domain of `sub` with `js` denoting the `s`-th element of `j...`, such that `js` is equal to `ik` minus `first[k]` where `map_rank[k]` equals `s` for all `s` in the range [0, `sub.rank()`). 

The special case makes the "`map_rank[k]` equals `s`" condition true.  Thus, `s` and `k` are the same here, so we're just subtracting each `i_k` by `first[k]` to get `j_k`.  In the above case, `j_0` equals `i_0 - 2`, `j_1` equals `i_1 - 3`, and `j_2` equals `i_2 - 4`.

The `map_rank[k]` business lets us describe subspans that have lower rank than the input.  It "shifts over" the index-of-the-multiindex `k`.  Otherwise, single `size_t` arguments `m` to `submdspan` work like a pair `tuple{m, m+1}`.

**Comment by seanbaxter** [comment]
I implemented things from the other direction. I compute which LayoutPolicy to use (left, right or stride) from paragraph 8, and go from there:

```cpp
  // If LayoutPolicy is layout_left and sub.rank() > 0 is true, then:
  // if is_convertible_v<Sk,full_extent_t> is true for all k in the range
  //   [0, sub.rank() - 1) and is_convertible_v<Sk,size_t> is false for k equal
  //   sub.rank()-1, then decltype(sub)::layout_type is layout_left.
  constexpr bool is_layout_left = layout_left == LP &&& (!rank2 |||
    (... && std::is_convertible_v<SliceSpecs...[0:rank2 - 1], full_extent_t>) &&&
    !std::is_convertible_v<SliceSpecs...[rank2 - 1], size_t>
  );

  // If LayoutPolicy is layout_right and sub.rank() > 0 is true, then:
  // if is_convertible_v<Sk,full_extent_t> is true for all k in the range
  //   [src.rank()-sub.rank()+1,src.rank()) and is_convertible_v<Sk,size_t>
  //   is false for k equal src.rank()-sub.rank(), 
  //   then decltype(sub)::layout_type is layout_right.
  constexpr size_t is_layout_right = layout_right == LP && (!rank2 |||
    (... && std::is_convertible_v<SliceSpecs...[rank - rank2 + 1:rank], full_extent_t>) &&
    !std::is_convertible_v<SliceSpecs...[rank - rank2], size_t>
  );
```

This is straight from the R14 proposal so I feel confident that it is correct. All three layout return types have the same pointer-offset calculation:
```cpp
  // * For size_t slice, skip the extent and stride, but add an offset
  //   corresponding to the value.
  // * For a std::full_extent, offset 0 and old extent.
  // * For a std::tuple, add an offset and add a new dynamic extent 
  //   (strides still preserved).
  size_t offset = src.mapping()(
    std::is_convertible_v<SliceSpecs, size_t> ??
      (size_t)slices :
    std::is_convertible_v<SliceSpecs, tuple> ??
      std::get<0>((tuple)slices) :
      0 ...
  );
```

The extents used in the return mapping is computed according to the proposal:
```cpp
  using Extents = extents<
    if std::is_convertible_v<SliceSpecs, tuple> => dynamic_extent else
    if std::is_convertible_v<SliceSpecs, full_extent_t> => Exts ...
  >; 
  constexpr size_t rank2 = Extents::rank();

  Extents dynamic_extents {
    if std::is_convertible_v<SliceSpecs, tuple> => 
      std::get<1>((tuple)slices) - std::get<0>((tuple)slices) 
    else if std::is_convertible_v<SliceSpecs, full_extent_t> && 
      dynamic_extent == Exts =>
      src.extent(int...) ...
  };
```

I bring everything together like so:
```cpp

  if constexpr(is_layout_left || is_layout_right) {
    // Use the source's layout policy.
    return mdspan<ET, Extents, LP, AP>(
      src.data() + offset,
      typename LP::template mapping<Extents>(dynamic_extents),
      src.accessor()
    );

  } else {
    // Use layout_stride policy.   
    std::array<size_t, Extents::rank()> strides {
      if !std::is_convertible_v<SliceSpecs, size_t> => src.stride(int...) ...
    };

    return mdspan<ET, Extents, layout_stride, AP>(
      src.data() + offset,
      layout_stride::mapping<Extents>(dynamic_extents, strides),
      src.accessor()
    );
  }
```

I never computed a `map_rank` or `first` or `last` arrays. I think those aren't really needed for the specification, and were invented because C++ doesn't allow filtering of template arguments in a straight forward way, so the dynamic extents ctor input is pretty tortured.

https://github.com/seanbaxter/mdspan/blob/circle/circle/experimental/mdspan#L679
Maybe this implementation has defects, but it passes all 45 test_submdspan tests.

**Comment by mhoemmen** [comment]
@seanbaxter wrote:
> I never computed a `map_rank` or `first` or `last` arrays. I think those aren't really needed for the specification, ... 

Right, they are exposition only.  I'm sure we would welcome ideas about how to word this more clearly.

I don't recall that we referenced any existing standards directly when coming up with the spec.  The Fortran Standard (e.g., Section 9.5.3.2, "Array element order," and 9.5.3.3, "Array sections") uses English words and is much less formal.  For example, here is Fortran's way of describing `submdspan` (9.5.3.3.1, para 1):

> The array section is the set of elements from the array determined by all possible subscript lists obtainable from the single subscripts or sequences of subscripts specified by each section subscript.

However, given that `mdspan` is more general than Fortran arrays, and C++ is not Fortran (phrases like "reference the same element" don't mean the same thing), it feels safer for `mdspan`'s description to be more formal.

@seanbaxter wrote:
> ... and were invented because C++ doesn't allow filtering of template arguments in a straight forward way, so the dynamic extents ctor input is pretty tortured.

Circle definitely does this in a nicer way than C++ : - ) .
