### ISSUE TITLE
layout_{left,right}::mapping(const extents_type&) needs MDSPAN_INLINE_FUNCTION

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/mdspan#175]
The `mapping(const extents_type&)` constructor in both `layout_left` and `layout_right` needs blessing with `MDSPAN_INLINE_FUNCTION`.  @youyu3 discovered this when attempting to construct an mdspan on device, with g++ 11.2.0 and nvcc 11.7.  It looks like the analogous `layout_stride::mapping` constructor already has this blessing.

**Comment by youyu3** [comment]
I think there are many other places that need this fix.  I built the tests with `nvcc` without the `--expt-relaxed-constexpr` flag and saw many warnings due to the missing `__host__ __device__`.  In `layout_{left,right}`, for example, `__compute_offset` and `operator()` need this fix as well, but there may be other places that existing tests don't cover.

@crtrott Are there plans to address this for all the occurrences (before I try to fix the above ones in `layout_{left,right}`)?

**Comment by crtrott** [comment]
There is a more fundamental issue: we use stuff like std::array, pair and tuple internally ...

The question is should we try and make all those ho away so the code would work without the constexpr relaxation

**Comment by youyu3** [comment]
True... Besides using equivalents (array, tuple, etc.) in libcudacxx, what options are there?

**Comment by mhoemmen** [comment]
@youyu3 @crtrott For the reference implementation, we could constrain those functions to take arbitrary "array-like" or "tuple-like" types, instead of requiring those types specifically.  That would let us sub in the libcudacxx equivalents, the Kokkos equivalents, or custom types that have the aroma of array or tuple.  This should make it easier for existing Kokkos or libcucxx users to introduce mdspan into their code, and should also reduce our libcucxx porting overhead.

**Comment by mhoemmen** [comment]
Fixed by PR #184.
